version: '3'

services:
  expedition_merman_events_listener:
    build:
      context: .
      dockerfile: ./compose/merman_wrapper/Dockerfile
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    command: python manage.py run_firebird_events_listener

  expedition_merman_wrapper:
    build:
      context: .
      dockerfile: compose/merman_wrapper/Dockerfile
    volumes:
      - expedition_merman_wrapper_logs:/application/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    command: python manage.py uwsgi
    env_file:
      - .env

  expedition_merman_celery:
    build:
      context: .
      dockerfile: ./compose/merman_wrapper/Dockerfile
    env_file:
      - .env
    depends_on:
      - expedition_merman_wrapper
      - redis
      - rabbitmq
    links:
      - expedition_merman_wrapper
      - redis
      - rabbitmq
    command: python manage.py run_celery

  redis:
    image: redis:latest
    expose:
      - "6379"

  rabbitmq:
    image: rabbitmq:3.7-alpine
    expose:
      - "5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
    expedition_merman_wrapper_logs:
    rabbitmq_data:
